Fix dev
JSerZANP/shaku pull request #13
Opened 2023-05-31 03:37 UTC by Chanyon

2023-06-01 06:18 UTC, JSerZANP commented
This change swallows the ending tag even when it is not part of shaku, which is not cool.

<img width="1107" alt="Screenshot 2023-06-01 at 15 13 50" src="https://github.com/JSerZANP/shaku/assets/69352453/afaf48f7-687f-4a37-98d0-52ab7db0dd09">

You can try it out on the above vercel depoloyement.

The dangling issue only occurs when **we have to add a comment block to annotate**, so I think it is better to 
only filter out such cases. 

One possible solution here is, when we traverse all the lines, we can find the comment blocks. 
For a comment block, if all the lines are shaku lines and the last line is only an ending tag, then we should suppress the ending tag.

2023-06-01 11:46 UTC, Chanyon commented
I add a flag `isShaKuLine = true` for Judging.(我添加了一个flag用于判断)

2023-06-01 13:33 UTC, JSerZANP requested changes

2023-06-01 13:33 UTC, JSerZANP commented on packages/shaku-code-annotate/src/__tests__/index.test.ts
> +  test("  */", async () => {
This is not what we want, you are treating all  `       */`  as shaku-specific stuff

2023-06-01 13:34 UTC, JSerZANP commented on packages/shaku-code-annotate/src/index.ts
> +type ShakuCommentEnd = {
we don't want this directive.

2023-06-05 01:15 UTC, JSerZANP requested changes

2023-06-05 01:15 UTC, JSerZANP commented on packages/remark-shaku-code-annotate/src/index.ts
> +        isShaKuLine = true;
this assumes comment block all starts with `/*`? which is not solid
also all shaku lines should be supported

2023-06-05 01:15 UTC, JSerZANP commented on packages/remark-shaku-code-annotate/src/index.ts
> +  let isShaKuLine = false;
maybe it should be named as `isShakuBlock`?

2023-06-05 01:15 UTC, JSerZANP commented on packages/remark-shaku-code-annotate/src/index.ts
> +      const commentBlockEnd = /^(?<leadingSpaces>\s*)\*\//.test(line[0].content);
this assumes all comment block ends with `*/`, which is not solid.
also it might be better put in `parseComment()`

2023-06-06 11:15 UTC, Chanyon commented
Thank you review! I can't fix this bug.

2023-06-06 11:15 UTC, closed without merging